version: '3.8'
services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
      POSTGRES_USER: go
      POSTGRES_PASSWORD: go
      POSTGRES_DB: go
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:5.1
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5433:80
volumes:
  postgres_volume:
